parameters:
#    grupon_menu.example.class: Grupon\MenuBundle\Example

services:
#    grupon_menu.example:
#        class: %grupon_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:

    acme_main.menu.sidebar:
        class: Knp\Menu\MenuItem
        factory_service: grupon_hello.menu_builder
        factory_method: createSidebarMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sidebar } # Named "sidebar" this time