grupon_contact:
    resource: "@GruponContactBundle/Resources/config/routing.yml"
    prefix:   /

grupon_admin:
    resource: "@GruponAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
grupon_user:
    resource: "@GruponUserBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"