parameters:
#    grupon_message.example.class: Grupon\MessageBundle\Example

services:
#    grupon_message.example:
#        class: %grupon_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
